RANDOM_SEED: 42
SLA_MS: 2200
FAIL_BUDGET: 0.02
SLA_BUDGET: 0.05
TIME_SPLIT_FRAC: 0.80
ROUTING_FAIL_BUDGET_MULT: 6.0
MIN_REQUESTS_POLICY: 60
MIN_REQUESTS_SLICE: 60
MAX_LATENCY_MISSING_RATE: 0.05
MAX_COST_MISSING_RATE: 0.05
REVIEW_COST: 2.0
TRIAGE_FN_COST_USD: 40.0
FAILURE_EVENT_COST_USD: 40.0
SLA_BREACH_PENALTY_USD: 5.0
CAPACITY_PER_DAY: 200
CAPACITY_P90_GUARD: 250
DAILY_COST_BUDGET_USD: 60.0
